#!/bin/sh
cd `dirname "$0"` || exit $?
mkdir -p built || exit $?
rm -rf built/*
(cd control &&\
     tar --numeric-owner --group=0 --owner=0 -czf ../built/control.tar.gz *)
(cd data &&\
     tar --numeric-owner --group=0 --owner=0 -czf ../built/data.tar.gz *)
cp -p debian-binary built/ || exit $?
cd built || exit $?
tar --numeric-owner --group=0 --owner=0 -czf dnsmore_1.2_all.ipk\
    debian-binary data.tar.gz control.tar.gz\
    || exit $?
